### PR TITLE
Update references for `1uc/sketch-golden-tests`.

### PR DESCRIPTION
**Pull request by 1uc**

### CODE REVIEW

**Review by pramodk — APPROVED** [review]
LGTM (I guess it would be useful/interesting once we start looking into diffs)

**Comment by 1uc** [comment]
Yes, though I find it helpful to see the generated code. Say if one's deep into a refactor, it might be nice to know what it used to generated. I've wanted to look at the analog of these for `nocmodl`.

**Comment by pramodk** [comment]
A trivialthing: should we enable option to automatically deleting branch on PR merge?

**Comment by 1uc** [comment]
That's where things get a bit ugly. The PR over at `BlueBrain/nmodl` still refers to this SHA. If we delete this branch, I don't know if the commit stays alive.

**Comment by 1uc** [comment]
I first want to see/feel how much having the these automatically generated diffs helps.

**Comment by 1uc** [comment]
Okay, let's try. It now automatically deletes, and enforces a linear history.

**Pull request merged**
